<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PackageExtractor</AssemblyName>
    <RootNamespace>PackageExtractor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\sbox-public\engine\Sandbox.Compiling\Sandbox.Compiling.csproj" />
  </ItemGroup>
</Project>
